name: "Build contracts"
on:
  - push

jobs:
  simplecoin-checks:
    name: "SimpleCoin: end-to-end tests"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: cd hardhat && yarn install
      - name: Deploy contract
        run: |
          make deploy_simple_coin > deploy.log
          cat deploy.log
        env:
          PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      - name: Test contract
        run: |
          WALLET_ADDRESS=$(awk '/Wallet Ethereum Address:/{print $NF}' deploy.log)
          CONTRACT_ADDRESS=$(sed -nr 's/.*deployed at ([^ ]+).*/\1/p' deploy.log)
          echo $WALLET_ADDRESS
          echo $CONTRACT_ADDRESS
          cd hardhat && yarn hardhat get-balance --contract $CONTRACT_ADDRESS --account $WALLET_ADDRESS
        env:
          PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  api-checks:
    name: "Filecoin APIs: end-to-end tests"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: |
          yarn install
          cd hardhat && yarn install
      - name: Deploy contracts
        run: |
          make deploy_api > deploy.log
          cat deploy.log
        env:
          PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      - name: Test contracts
        run: |
          WALLET_ADDRESS=$(awk '/Wallet Ethereum Address:/{print $NF}' deploy.log)
          CONTRACT_ADDRESS=$(sed -nr 's/.*deployed at ([^ ]+).*/\1/p' deploy.log)
          echo "WALLET_ADDRESS $WALLET_ADDRESS"
          echo "CONTRACT_ADDRESS $CONTRACT_ADDRESS"
          CONTRACT_ADDRESS=$CONTRACT_ADDRESS make test_cbor_serialization
        env:
          PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}


