name: "Security checks"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  account:
    name: "Account API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_account_api

  power:
    name: "Power API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_power_api

  verifreg:
    name: "VerifReg API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_verifreg_api

  market:
    name: "Market API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_market_api

  miner:
    name: "Miner API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_miner_api

  datacap:
    name: "DataCap API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_datacap_api

  send:
    name: "Send API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_send_api

  precompiles:
    name: "Precompiles API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_precompiles_api

  init:
    name: "Init API"
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      - name: Install mythril
        run: pip3 install mythril
      - name: Run checks
        run:  make security_init_api
